Fix Fix missing distribution buildout error.
The hack for renaming the script to the buildout part name caused
the buildout exception:

    While:
      Installing translations.
      Getting distribution for 'translations'.
    Error: Couldn't find a distribution for 'translations'.

This disables the renaming feature.